patterns:
  timestamp: "(?P<timestamp>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})"
  level: "LVL:(?P<level>INFO|WARNING|ERROR)"
  message: "MSG=(?P<message>.*?)(?= \\||$)"
  ip: "IP=(?P<ip>[\\d\\.]+)"
